import {
  HiOutlineExclamationCircle,
  HiOutlineDotsVertical,
  HiOutlineDocumentText,
  HiOutlineDocumentAdd,
  HiOutlineExclamation,
  HiOutlineLockClosed,
  HiOutlineViewBoards,
  HiOutlineFolderAdd,
  HiOutlineLockOpen,
  HiOutlineDatabase,
  HiOutlineTemplate,
  HiOutlineCalendar,
  HiOutlineChartBar,
  HiOutlineMailOpen,
  HiOutlineViewGrid,
  HiOutlineEmojiSad,
  HiOutlineUserAdd,
  HiOutlineSearch,
  HiOutlineLogout,
  HiOutlinePencil,
  HiOutlineTrash,
  HiOutlineCheck,
  HiOutlineClock,
  HiOutlineBell,
  HiOutlineMail,
  HiOutlineSave,
  HiOutlineCog,
  HiOutlineEye,
  HiPaperClip,
  HiHashtag,
  HiHeart,
  HiMenu,
  HiLink,
} from "react-icons/hi";
import {
  HiOutlineChatBubbleLeftRight,
  HiOutlineExclamationTriangle,
  HiOutlineUserCircle,
  HiDevicePhoneMobile,
  HiOutlineUserGroup,
  HiOutlineFaceSmile,
  HiOutlineUser,
  HiOutlineStar,
  HiOutlineSun,
} from "react-icons/hi2";
import { IoIosSend } from "react-icons/io";
import {
  IoCheckmarkCircleOutline,
  IoChevronDownOutline,
  IoCloseCircleOutline,
  IoMailUnreadOutline,
  IoArrowBackOutline,
  IoWarningOutline,
  IoChevronForward,
  IoLogoInstagram,
  IoLogoFacebook,
  IoChevronBack,
  IoChevronUp,
  IoClose,
  IoSend,
} from "react-icons/io5";
import { LuGoal, LuCalendarPlus, LuListTodo } from "react-icons/lu";
import {
  CgCornerDoubleUpLeft,
  CgCornerUpRight,
  CgCornerUpLeft,
} from "react-icons/cg";
import { TbTemplate, TbMailPlus, TbWorld, TbEdit } from "react-icons/tb";
import {
  MdOutlineInsertEmoticon,
  MdOutlineMarkChatUnread,
  MdOutlineEmojiEvents,
  MdOutlineEventNote,
  MdOutlineCategory,
  MdOutlinePercent,
  MdOutlinePlace,
  MdOutlineSell,
  MdHistory,
  MdCircle,
  MdTitle,
} from "react-icons/md";
import { BsFilter, BsTelephone, BsMoonStars } from "react-icons/bs";
import {
  AiOutlineFundProjectionScreen,
  AiOutlinePaperClip,
  AiOutlineIdcard,
  AiOutlinePlus,
  AiOutlineCar,
} from "react-icons/ai";
import { BiMailSend, BiBellPlus, BiCrown } from "react-icons/bi";
import { PiRobot, PiFolderSimpleDashed } from "react-icons/pi";

export {
  AiOutlineFundProjectionScreen,
  HiOutlineChatBubbleLeftRight,
  HiOutlineExclamationTriangle,
  HiOutlineExclamationCircle,
  IoCheckmarkCircleOutline,
  MdOutlineMarkChatUnread,
  MdOutlineInsertEmoticon,
  HiOutlineDotsVertical,
  HiOutlineDocumentText,
  MdOutlineEmojiEvents,
  CgCornerDoubleUpLeft,
  HiOutlineDocumentAdd,
  PiFolderSimpleDashed,
  IoChevronDownOutline,
  IoCloseCircleOutline,
  HiOutlineExclamation,
  IoMailUnreadOutline,
  HiOutlineUserCircle,
  HiDevicePhoneMobile,
  HiOutlineLockClosed,
  HiOutlineViewBoards,
  MdOutlineEventNote,
  IoArrowBackOutline,
  HiOutlineFolderAdd,
  AiOutlinePaperClip,
  HiOutlineUserGroup,
  HiOutlineFaceSmile,
  HiOutlineLockOpen,
  HiOutlineDatabase,
  HiOutlineEmojiSad,
  HiOutlineTemplate,
  HiOutlineCalendar,
  HiOutlineChartBar,
  HiOutlineMailOpen,
  MdOutlineCategory,
  HiOutlineViewGrid,
  MdOutlinePercent,
  HiOutlineUserAdd,
  IoWarningOutline,
  IoChevronForward,
  CgCornerUpRight,
  HiOutlineSearch,
  HiOutlineLogout,
  HiOutlinePencil,
  AiOutlineIdcard,
  IoLogoInstagram,
  LuCalendarPlus,
  HiOutlineClock,
  MdOutlinePlace,
  HiOutlineTrash,
  HiOutlineCheck,
  CgCornerUpLeft,
  IoLogoFacebook,
  MdOutlineSell,
  HiOutlineStar,
  AiOutlinePlus,
  HiOutlineUser,
  HiOutlineBell,
  HiOutlineMail,
  HiOutlineSave,
  IoChevronBack,
  AiOutlineCar,
  HiOutlineCog,
  HiOutlineEye,
  HiOutlineSun,
  IoChevronUp,
  BsTelephone,
  HiPaperClip,
  BsMoonStars,
  BiBellPlus,
  TbTemplate,
  TbMailPlus,
  BiMailSend,
  LuListTodo,
  MdHistory,
  HiHashtag,
  IoIosSend,
  BsFilter,
  MdCircle,
  PiRobot,
  MdTitle,
  IoClose,
  HiHeart,
  BiCrown,
  TbWorld,
  LuGoal,
  TbEdit,
  HiLink,
  HiMenu,
  IoSend,
};
