import {
  HiOutlineExclamationCircle,
  HiOutlineDotsVertical,
  HiOutlineDocumentText,
  HiOutlineDocumentAdd,
  HiOutlineExclamation,
  HiOutlineLockClosed,
  HiOutlineViewBoards,
  HiOutlineFolderAdd,
  HiOutlineLockOpen,
  HiOutlineDatabase,
  HiOutlineTemplate,
  HiOutlineCalendar,
  HiOutlineChartBar,
  HiOutlineMailOpen,
  HiOutlineViewGrid,
  HiOutlineEmojiSad,
  HiOutlineUserAdd,
  HiOutlineSearch,
  HiOutlineLogout,
  HiOutlinePencil,
  HiOutlineTrash,
  HiOutlineCheck,
  HiOutlineClock,
  HiOutlineBell,
  HiOutlineMail,
  HiOutlineSave,
  HiOutlineCog,
  HiOutlineEye,
  HiPaperClip,
  HiHashtag,
  HiHeart,
  HiMenu,
  HiLink,
} from "react-icons/hi";
import {
  HiOutlineChatBubbleLeftRight,
  HiOutlineExclamationTriangle,
  HiOutlineUserCircle,
  HiDevicePhoneMobile,
  HiOutlineUserGroup,
  HiOutlineFaceSmile,
  HiOutlineUser,
  HiOutlineStar,
  HiOutlineSun,
} from "react-icons/hi2";
import { IoIosSend } from "react-icons/io";
import {
  IoCheckmarkCircleOutline,
  IoChevronForwardOutline,
  IoChevronDownOutline,
  IoChevronBackOutline,
  IoCloseCircleOutline,
  IoMailUnreadOutline,
  IoChevronUpOutline,
  IoArrowBackOutline,
  IoWarningOutline,
  IoChevronForward,
  IoLogoInstagram,
  IoLogoFacebook,
  IoLogoWhatsapp,
  IoOpenOutline,
  IoChevronBack,
  IoChevronUp,
  IoClose,
  IoSend,
} from "react-icons/io5";
import {
  LuChevronsUpDown,
  LuCalendarPlus,
  LuFolderOutput,
  LuFolderInput,
  LuListTodo,
  LuFolder,
  LuMailX,
  LuGoal,
} from "react-icons/lu";
import {
  CgCornerDoubleUpLeft,
  CgCornerUpRight,
  CgCornerUpLeft,
} from "react-icons/cg";
import {
  TbStarFilled,
  TbTemplate,
  TbMailPlus,
  TbStarOff,
  TbReload,
  TbClick,
  TbWorld,
  TbEdit,
  TbStar,
} from "react-icons/tb";
import {
  MdOutlineInsertEmoticon,
  MdOutlineAlternateEmail,
  MdOutlineMarkChatUnread,
  MdOutlineDragIndicator,
  MdOutlineAccessAlarms,
  MdOutlineVideoLibrary,
  MdOutlineEmojiEvents,
  MdOutlineEventNote,
  MdOutlineCategory,
  MdOutlinePercent,
  MdOutlineAlarmOn,
  MdArrowDropDown,
  MdOutlineImage,
  MdOutlineTitle,
  MdOutlinePlace,
  MdOutlineSell,
  MdAlarmAdd,
  MdNumbers,
  MdHistory,
  MdCircle,
  MdTitle,
} from "react-icons/md";
import { BsFilter, BsTelephone, BsMoonStars } from "react-icons/bs";
import {
  AiOutlineFundProjectionScreen,
  AiOutlinePaperClip,
  AiOutlineIdcard,
  AiOutlinePlus,
  AiOutlineCar,
} from "react-icons/ai";
import {
  BiMailSend,
  BiBellPlus,
  BiCrown,
  BiTask,
  BiAlarmOff,
} from "react-icons/bi";
import {
  PiRobot,
  PiFolderSimpleDashed,
  PiStepsBold,
  PiWarningCircleBold,
} from "react-icons/pi";
import {
  FaFacebookF,
  FaChartLine,
  FaChartColumn,
  FaRegFilePowerpoint,
  FaAt,
  FaDollarSign,
} from "react-icons/fa6";
import { RiDeviceRecoverLine } from "react-icons/ri";
import { GrDocumentExcel } from "react-icons/gr";
import { FaQuestion } from "react-icons/fa6";
import { RxDragHandleDots2 } from "react-icons/rx";
import { LiaIdCard } from "react-icons/lia";

export {
  AiOutlineFundProjectionScreen,
  HiOutlineChatBubbleLeftRight,
  HiOutlineExclamationTriangle,
  HiOutlineExclamationCircle,
  IoCheckmarkCircleOutline,
  IoChevronForwardOutline,
  MdOutlineMarkChatUnread,
  MdOutlineInsertEmoticon,
  MdOutlineAlternateEmail,
  MdOutlineDragIndicator,
  MdOutlineVideoLibrary,
  HiOutlineDotsVertical,
  HiOutlineDocumentText,
  MdOutlineAccessAlarms,
  IoChevronBackOutline,
  MdOutlineEmojiEvents,
  CgCornerDoubleUpLeft,
  HiOutlineDocumentAdd,
  PiFolderSimpleDashed,
  IoChevronDownOutline,
  IoCloseCircleOutline,
  HiOutlineExclamation,
  PiWarningCircleBold,
  FaRegFilePowerpoint,
  RiDeviceRecoverLine,
  IoMailUnreadOutline,
  HiOutlineUserCircle,
  HiDevicePhoneMobile,
  HiOutlineLockClosed,
  HiOutlineViewBoards,
  IoChevronUpOutline,
  MdOutlineEventNote,
  IoArrowBackOutline,
  HiOutlineFolderAdd,
  AiOutlinePaperClip,
  HiOutlineUserGroup,
  HiOutlineFaceSmile,
  RxDragHandleDots2,
  HiOutlineLockOpen,
  HiOutlineDatabase,
  HiOutlineEmojiSad,
  HiOutlineTemplate,
  HiOutlineCalendar,
  HiOutlineChartBar,
  HiOutlineMailOpen,
  MdOutlineCategory,
  HiOutlineViewGrid,
  MdOutlinePercent,
  HiOutlineUserAdd,
  IoWarningOutline,
  IoChevronForward,
  LuChevronsUpDown,
  MdOutlineAlarmOn,
  CgCornerUpRight,
  HiOutlineSearch,
  HiOutlineLogout,
  HiOutlinePencil,
  AiOutlineIdcard,
  MdArrowDropDown,
  GrDocumentExcel,
  IoLogoInstagram,
  MdOutlineTitle,
  MdOutlineImage,
  IoLogoWhatsapp,
  LuCalendarPlus,
  HiOutlineClock,
  MdOutlinePlace,
  HiOutlineTrash,
  HiOutlineCheck,
  CgCornerUpLeft,
  IoLogoFacebook,
  LuFolderOutput,
  LuFolderInput,
  MdOutlineSell,
  FaChartColumn,
  HiOutlineStar,
  IoOpenOutline,
  AiOutlinePlus,
  HiOutlineUser,
  HiOutlineBell,
  HiOutlineMail,
  HiOutlineSave,
  IoChevronBack,
  AiOutlineCar,
  HiOutlineCog,
  HiOutlineEye,
  HiOutlineSun,
  TbStarFilled,
  FaDollarSign,
  FaFacebookF,
  PiStepsBold,
  FaChartLine,
  IoChevronUp,
  BsTelephone,
  HiPaperClip,
  BsMoonStars,
  BiBellPlus,
  FaQuestion,
  TbTemplate,
  TbMailPlus,
  BiMailSend,
  LuListTodo,
  BiAlarmOff,
  MdAlarmAdd,
  MdHistory,
  HiHashtag,
  IoIosSend,
  TbStarOff,
  MdNumbers,
  LiaIdCard,
  TbReload,
  BsFilter,
  MdCircle,
  LuFolder,
  PiRobot,
  MdTitle,
  IoClose,
  HiHeart,
  TbClick,
  BiCrown,
  TbWorld,
  LuMailX,
  TbStar,
  BiTask,
  LuGoal,
  TbEdit,
  HiLink,
  HiMenu,
  IoSend,
  FaAt,
};
