// <--------------------------------------------------------------------->
// - Conservar esta estructura para que no se vean afectados los estilos -
// <--------------------------------------------------------------------->
// Basic Components
import { Sidebar } from "@/components/sidebar/Sidebar";
import { GlobalContainer } from "@/components/container/GlobalContainer";
// App Global Styles
import "./globals.css";
// Mantine configuration
import {
  MantineProvider,
  ColorSchemeScript,
  Container,
  Flex,
} from "@mantine/core";
// Mantine Global theme configuration
import { theme } from "../theme/CustomTheme";
// Mantine Dependencies Styles
import "@mantine/core/styles.css";
import "@mantine/tiptap/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/notifications/styles.css";
// import '@mantine/charts/styles.css';
// <--------------------------------------------------------------------->
// Next/Metadata
import type { Metadata } from "next";
// Next/fonts
import { Inter } from "next/font/google";
import { Notifications } from "@mantine/notifications";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantineProvider theme={theme} defaultColorScheme="light">
          <Container fluid px={0}>
            <Notifications />
            <Flex p={0} >
              <Sidebar />
              <GlobalContainer>{children}</GlobalContainer>
            </Flex>
          </Container>
        </MantineProvider>
      </body>
    </html>
  );
}
